/// String Base64 limpio y formateado para Silueta.jpg
const String kSiluetaBase64Clean =
    '/9j/4AAQSkZJRgABAQEAswCzAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/wAALCAHCAcIBASIA/8QAHAABAAIDAQEBAAAAAAAAAAAAAAUGAwQHAgEI/8QATBAAAQQBAQMIBwMICQMEAgMAAQACAwQFEQYSIQcUMUFRYZKxEzRUcXOBkSIyQhUjM1JicqHBFiRDU4KistHwJTxmg5Oj5PY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD5/ooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigA/n/AM96sVL1OD4bfJZkRERERERERERERERERERERERERERERERERERERFVLvrk/xHeZVlpepwfDb5LMiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIqpd9cn+I7zKstL1OD4bfJZkRERERERERERERFXtpNs8Fs64R5K8wWT92tEDJK73MbqVVp9udqcoNNl9irm477tjJPEDffu66/xWlJi+VjKgmfM4fEMd+CCPfI+eh81rv5Mdr7bTz/AJQr+8ekRNcB/qCwnkYyTtXP25yxeek6O/8AmvDOSHaOsNaW32Qa8dGoeB/rXpuyXKpi9XY/a6teA6GWNTr4mnzXtm1PKjg9PyzstXykI6X1D9o+EnyUph+WfAzzitna17B2ugttRHd1944/UBdGx2Qp5Ks2xj7UNmB3ESRPDgfmFsoiIiIiIiIiIiIiIqpd9cn+I7zKstL1OD4bfJZkRERERERERERERVjO3JLtz8nsvuxtUjWSaMazSDr3eBDG9Refl2rewGzmGw0e/iqULHv+06f78kneXnUn6qZREREWnk8VQykBhyVKvaiI03Zow8fxVGtclWPqWnXdkshd2eu9OtZ5fE7ucx3SO5bVXPbSbPERbXY4XqbeH5UxjS4AdskX3h7xqFc8feq5GpHaoWI7FeQatkjdqCthEREREREREREREVUu+uT/Ed5lWWl6nB4fv9x/d/l3g69ggljnhZLC9skT2hzXtOocD0EFe0REREREREREVUu+uT/Ed5lWWl6nB4fv9x/d/l3g69ggljnhZLC9skT2hzXtOocD0EFe0REREREREREVUu+uT/Ed5lWWl6nB4fv/Z';

/// Función auxiliar para formatear y padear strings base64 evitando FormatException
String padBase64String(String input) {
  final clean = input.replaceAll(RegExp(r'\s+'), '');
  final remainder = clean.length % 4;
  if (remainder == 0) return clean;
  return clean + ('=' * (4 - remainder));
}
